### ISSUE TITLE
Add user's data

### ISSUE THREAD

**Issue by kcrebound** [lunahq/flutter-crisp#12]
I want to add some data for user like the app version and so on

![image](https://user-images.githubusercontent.com/151965/115576334-d7164d80-a2dc-11eb-9d09-461d0d4cec7b.png)

I need to use webview javascript method for this?

**Comment by f2acode** [comment]
@kcrebound yes, inside our code there is a function called `appendScript` where we add the user data. You can go on and open an PR to add more fields you find useful (I can't do it now) :smile:
