### ISSUE TITLE
crisp in ios

### ISSUE THREAD

**Issue by Bunny1376** [lunahq/flutter-crisp#13]
hi , wish you best!
i am using crisp in my aoolication it is ok in android but i have problem in ios, in ios side it opens a browser page and does not behave as a widget

**Comment by f2acode** [comment]
Hey! Thank you, I wish you the same!
I don't have a Mac to test it out, I would need somebody else to fix this error.

**Comment by kcrebound** [comment]
fix works good on iOS and Android

![image](https://user-images.githubusercontent.com/151965/120076672-362b6700-c0c0-11eb-8630-6779f79285f2.png)

![image](https://user-images.githubusercontent.com/151965/120076703-6541d880-c0c0-11eb-9d74-e4b9650547d5.png)

**Comment by vishnukvmd** [comment]
@f2acode Hey, @kcrebound's changes seem to be working quite well. Can we please merge this? Thank you!

**Comment by f2acode** [comment]
@vishnukvmd Done!
