### ISSUE TITLE
set user detail

### ISSUE THREAD

**Issue by Bunny1376** [lunahq/flutter-crisp#14]
hey! hope you be well!
I am using crisp: ^0.1.6 and my flutter version is 2.2.0
I send user detail in CrispMain() but I receive the message as a visitor
what should I do?
CrispView(
                          crispMain: CrispMain(
                              websiteId: 'test',
                              user: CrispUser(
                                avatar: 'test',
                                email: 'test@test.com',
                                nickname: 'test',
                                phone: '5555',
                              )))
thank you.

**Comment by f2acode** [comment]
Hey! I hope you too! Sorry for the delay! 
I just tested, it's working as described on the docs. Now you can also set more options with `setSessionData` too.
