### ISSUE TITLE
AppBar not showing

### ISSUE THREAD

**Issue by kcrebound** [lunahq/flutter-crisp#16]
![image](https://user-images.githubusercontent.com/151965/120076793-cbc6f680-c0c0-11eb-9fdb-25ce73d64f98.png)

**Comment by kcrebound** [comment]
Use bypass with `Scaffold AppBar` I think it is a more general way

```dart
class SupportPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('support'),
      ),
      body: CrispView(
        loadingWidget: Center(
          child: CircularProgressIndicator(),
        ),
        crispMain: SupportController.to.crispMain,
      ),
    );
  }
}
```

**Comment by f2acode** [comment]
@kcrebound I don't see this as a bug, the lib used to receive the `AppBar` but making a view that you can wrap is more flexible.
