### ISSUE TITLE
CrispView not fitting the entire scaffhold

### ISSUE THREAD

**Issue by yoannpicquenot** [lunahq/flutter-crisp#19]
Hi,

I'm having trouble with the size of the crispView on iOs devices. In Android, it works well. (see picture below)

Context:

```
Scaffhold:
-> LayoutWidget
     -> Stack
          -> Offstage( DashboardPage )
          -> Offstage( ChatPage )
               -> CrispView // problem here
          -> Offstage( AccountPage )
     -> BottomNavigationBar
```

When I remove the Offstage, the CrispView fits the entire screen.
I don't want to get rid of the offstage.

Does anyone have a workaround or not how to fix this issue?

![Image d’iOS](https://user-images.githubusercontent.com/6999772/126642308-ce1878ac-88a2-4bd2-a3f8-b3b47da8fe02.png)

**Comment by f2acode** [comment]
Since it will fit the entire screen I think you don't need to wrap the crisp in the chat page, so you would be able to make two different pages if you need a chat page.

```
Scaffhold:
-> LayoutWidget
     -> Stack
          -> Offstage( DashboardPage )
          -> Offstage( ChatPage )
          -> CrispView // other different page
          -> Offstage( AccountPage )
     -> BottomNavigationBar
```

What do you think?

**Comment by f2acode** [comment]
No, to render `CrispView` in the space I just sent. Instead of above `Offstage` it would be above `Stack`

**Comment by yoannpicquenot** [comment]
From what I can understand:

```
Scaffhold:
-> LayoutWidget
     -> CrispView (//above Stack)
     -> Stack
          -> Offstage( DashboardPage )
          -> Offstage( AccountPage )
     -> BottomNavigationBar
```

Is it so?

**Comment by f2acode** [comment]
I think that can work, but I think it could be `CrispView` inside `Stack` too I think, as I sent.

**Comment by yoannpicquenot** [comment]
If I let the CrispView inside my stack, I'll need the OffStage to hide it though.

**Comment by f2acode** [comment]
Hey, since there isn't any update here and it's a more code layout issue and not direct related to this library, I'm gonna close this issue. If you still have problems Stackoverflow would be a better place to ask for help in this case. :smiley:
