### ISSUE TITLE
file upload is broken

### ISSUE THREAD

**Issue by jackdreilly** [lunahq/flutter-crisp#2]
I cannot upload files on android.

If you click "+", it opens the file browser. Then I select a file, and then it restarts the webview

**Comment by jackdreilly** [comment]
I just tried with the example project, and same, it does not work.

I'm debugging on a android motox4

**Comment by jackdreilly** [comment]
Note that the regular chat works fine

**Comment by jackdreilly** [comment]
Wow, that took me way too long to track down, but it's this line: https://github.com/lunahq/flutter-crisp/blob/master/lib/crisp_view.dart#L35

If you comment out that line, file uploading works.

Why was the `reload` call necessary?

**Comment by f2acode** [comment]
Hey @jackdreilly it's due to a bug in WebView library, the keyboard stop working when we go to a browser (by opening a link for example), I'm gonna put a flag for that to avoid reload with opening file upload. Thank you for the feedback!
