### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by TobiCrackIT** [lunahq/flutter-crisp#20]
The CrispView takes some time to load even when the CrispMain has been pre-registered. Is there a way to make it load faster?

**Comment by f2acode** [comment]
Can you provide more details? I would think it depends on the internet type/speed and device specification.
We don't have any config for performance improvement.

**Comment by ccfiel** [comment]
maybe this can be implemented @f2acode  https://github.com/pichillilorenzo/flutter_inappwebview/issues/749#issuecomment-811905600 

```So, if you need to display that webpage and you know that won't change over time or you somehow know that changes are not so frequent, you can load the first time using the default AndroidCacheMode.LOAD_DEFAULT and then use AndroidCacheMode.LOAD_CACHE_ONLY for all the other times.
Or also use a HeadlessInAppWebView to load it the first time using the default AndroidCacheMode.LOAD_DEFAULT and then load your InAppWebView widget using AndroidCacheMode.LOAD_CACHE_ONLY.
```
so that it will load faster.

**Comment by f2acode** [comment]
Hey @ccfiel and @TobiCrackIT The webview already has a default cache, which is updated when expires. 
It's not possible to check if the webview is already cached after using `HeadlessInAppWebView` which can lead to UX problems.
I just added the `AndroidCacheMode.LOAD_CACHE_ELSE_NETWORK` option which ignore expiration for better improvement.
