### ISSUE TITLE
slow and sometime does not load

### ISSUE THREAD

**Issue by ccfiel** [lunahq/flutter-crisp#9]
slow in loading and sometime does not load. does crisp flutter has the same as this https://github.com/walterholohan/react-native-crisp-chat-sdk

**Comment by f2acode** [comment]
@ccfiel I just updated the package to use other library for web view, so maybe the behaviors you faced are fixed now. If not, can you provide some details about this?

**Comment by ccfiel** [comment]
thanks @f2acode I will and give feedback. thanks!
